mysql:
  image: mysql
  container_name: mysql
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_DATABASE: order_details
    MYSQL_ROOT_PASSWORD: morerin
    


php:
  image: php:fpm-alpine
  container_name: php
  volumes:
    - .:/var/www/order
  entrypoint:
    - php-fpm
  links:
    - mysql
  environment:
    NGIN_HOSTNAME: NGINX_HOSTNAME
    NGIN_PORT: NGINX_PORT


nginx:
  image: nginx:alpine
  container_name: nginx
  volumes_from:
    - php
  volumes:
    - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
  ports:
    - 3128:80